### ISSUE TITLE
Cannot find module 'tailwindcss/forms' error

### ISSUE THREAD

**Issue by aequis** [Barre/privaxy#10]
Hi, building the web frontend fails with the above error. 

Seems to be related to https://github.com/tailwindlabs/tailwindcss-forms/issues/31), since running 'npm install -D @tailwindcss/forms' fixes the error.

**Comment by dhc02** [comment]
I also encountered this error and ran `npm install` (with no further arguments) in the `web_frontend` folder and that fixed it. It's a dependency of an included package, apparently.

**Comment by aequis** [comment]
Oh, duh, I should've tried that first.
