### ISSUE TITLE
trunk build --release fails, missing "wasm32-unknown-unknown"

### ISSUE THREAD

**Issue by aequis** [Barre/privaxy#11]
Building the web frontend kept failing immediately until I ran "rustup target add wasm32-unknown-unknown"

edit: Should probably mention. This is on a Macbook Pro with M1.

**Comment by aequis** [comment]
Seems to be failing now after building and after downloading wasm-bindgen.

```
Finished release [optimized] target(s) in 27.94s
2022-05-20T13:30:59.416012Z  INFO fetching cargo artifacts
2022-05-20T13:30:59.581030Z  INFO processing WASM for web_frontend
2022-05-20T13:30:59.593944Z  INFO downloading wasm-bindgen version="0.2.80"
2022-05-20T13:30:59.595278Z ERROR ❌ error
error from HTML pipeline

Caused by:
    0: error from asset pipeline
    1: failed downloading release archive
    2: unsupported architecture
Error: error from HTML pipeline

Caused by:
    0: error from asset pipeline
    1: failed downloading release archive
    2: unsupported architecture
```

**Comment by aequis** [comment]
Found this comment in one of the issues in wasm-bindgen: https://github.com/rustwasm/wasm-bindgen/issues/2723#issuecomment-971086798

Running `cargo install --locked wasm-bindgen-cli` allows me to successfully build the web frontend.

**Comment by Barre** [comment]
This can be fixed by installing rust's wasm target `rustup target add wasm32-unknown-unknown` 

I updated the readme accordingly in bc6a8b7f8beda43453ca2714defdd3775ff7da93.
