### ISSUE TITLE
Initial release

### ISSUE THREAD

**Issue by Barre** [Barre/privaxy#2]
- [ ] Write proper documentation.
- [x] Keep only the most recent requests in the "Requests" pane of the gui.
- [x] Serve the gui from the server instead of from trunk.

**Comment by Darthagnon** [comment]
Sorry to be "that guy". Will Windows ever be supported?

**Comment by Barre** [comment]
@Darthagnon There is no good reason not to, the codebase is not too platform specific and only few tweaks are probably required to make it work. 

In the meantime, it is possible to run privaxy through WSL.

**Comment by Darthagnon** [comment]
I'm really looking forward to following the project's development. With Manifest v3, it looks like exactly what's needed!

**Comment by whathappenedman** [comment]
Hi! 
1. You should implement irl rewriting with some predined options. Like reddit to teddit or old.reddit.
Some options exist for Twitter and such
2. Another major option would be automatically redirecting amp links to the original.
3. 
Also does this allow IP address blocking?

**Comment by shirshak55** [comment]
I can work on windows version :)

**Comment by shirshak55** [comment]
It seems to work fine

![image](https://user-images.githubusercontent.com/8097377/169449587-cbc926f9-d96f-4ef9-b200-e61366906dae.png)
