### ISSUE TITLE
Moderate-high RAM usage, internet throttling (Windows)

### ISSUE THREAD

**Issue by Darthagnon** [Barre/privaxy#23]
![Taskmgr_LLUzegQh0l](https://user-images.githubusercontent.com/20792748/174690755-b6ad4836-6a20-4e92-806d-bbbd28c74651.png)

Not sure if I'm doing something wrong, or if by default it uses many more filters than in the tests, but Privaxy uses around 100mb by default on Windows ( (I realise RAM usage will increase with number of filters used) and internet browsing feels slow. ~~Is there a way to run it silently without the console window?~~ I found out how to run Privaxy on Windows without a console window, using an old method.

![chrome_lyJg10BTR0](https://user-images.githubusercontent.com/20792748/174690850-efb4ecef-4b9b-4f6d-9599-1ea0f1619c39.png)

## Internet Speed Test:

Same speed with and without Privaxy, but there is a noticeable delay of a second or two when loading pages while Privaxy is running, while the same pages load instantly without Privaxy.
![Speedtest_vCW9kVG8tN](https://user-images.githubusercontent.com/20792748/174691060-525ac51f-4def-499e-b845-9f51526dec06.png)

Maybe HDD throttling? Not sure what the limiting factor is.

**Comment by Darthagnon** [comment]
# How to run Privaxy on Windows without an annoying CMD window
Also seems to halve the RAM usage when run this way.
![Taskmgr_HwqV02HfHt](https://user-images.githubusercontent.com/20792748/174691864-1d629cba-0cba-4d7b-8a10-a12507b5cc00.png)

1. Create a `run.bat` batch file next to `privaxy.exe` containing only the name of the executable, i.e. `privaxy.exe`
2. Create a `hide.vbs` script file in the same folder, and put the following code into it: `CreateObject("Wscript.Shell").Run """" & WScript.Arguments(0) & """", 0, False`
3. Create a New Shortcut (e.g. in `%APPDATA%\Microsoft\Windows\Start Menu\Programs\Startup\`, if you want to start Privaxy automatically with your PC) and put the following into the `Target:` field: `C:\Windows\System32\wscript.exe "D:\Absolute\Path\to\hide.vbs" "C:\Absolute\Path\to\run.bat"`
4. Run Privaxy via this shortcut will launch it without a console window, and it will use 1/2 the RAM it would otherwise.

**Comment by Darthagnon** [comment]
Hmmm... looks like it's not that simple. While running hidden via the above method and using less RAM, the GUI is accessible via the browser, but it seems to not work reliably, with ads or placeholders appearing (whereas running with the console open, it works perfectly).

**Comment by Barre** [comment]
Memory usage seems ok to me. 

On slowness, I did some troubleshooting. [Reqwest](https://github.com/seanmonstar/reqwest) by default uses system proxy settings which just makes privaxy forwards requests to privaxy. I didn't observe the same behavior on linux / macos though.

I also saw slowness coming from with trustdns with many related issues such as https://github.com/bluejekyll/trust-dns/issues/1607, https://github.com/bluejekyll/trust-dns/pull/1696, https://github.com/bluejekyll/trust-dns/issues/1636, let's use `getaddrinfo` everywhere then.

I fixed both issues in #24 and published a new release https://github.com/Barre/privaxy/releases/tag/v0.3.0

**Comment by Darthagnon** [comment]
Thank you!!! Confirm that it's a lot faster. Memory usage is about 100mb with standard filters enabled during standard usage, which is okay (voidtools Everything, Quicklook each take about that much).
