### ISSUE TITLE
Error compiling web_frontend ( arm64 )

### ISSUE THREAD

**Issue by supperchym23** [Barre/privaxy#31]
I have same issue like https://github.com/Barre/privaxy/issues/18 but on arm64, nodejs already upgrade (18.9).
warning: `web_frontend` (bin "web_frontend") generated 2 warnings
    Finished release [optimized] target(s) in 1m 17s
2022-09-23T18:03:21.417497Z  INFO fetching cargo artifacts
2022-09-23T18:03:21.541404Z  INFO processing WASM for web_frontend
2022-09-23T18:03:21.546225Z  INFO calling wasm-bindgen for web_frontend
2022-09-23T18:03:21.549376Z ERROR ❌ error
error from HTML pipeline

Caused by:
    0: error from asset pipeline
    1: error spawning wasm-bindgen call
    2: Exec format error (os error 8)
Error: error from HTML pipeline

Caused by:
    0: error from asset pipeline
    1: error spawning wasm-bindgen call
    2: Exec format error (os error 8)

Thanks!

**Comment by mzy2240** [comment]
Did you manage to solve the issue?

**Comment by Barre** [comment]
There is already a working pipeline for linux arm64 https://github.com/Barre/privaxy/blob/main/.github/workflows/ci.yml#L80

**Comment by mzy2240** [comment]
Still fails when building the web frontend, even with the latest version

**Comment by mzy2240** [comment]
I guess the trunk config, instead of CI, should be updated
