### ISSUE TITLE
M1 native build?

### ISSUE THREAD

**Issue by tkit0428** [Barre/privaxy#43]
You know rosetta eats ram

**Comment by Barre** [comment]
It's not yet possible to cross compile tauri https://tauri.app/v1/guides/building/cross-platform/ 

Github hosted m1 runners are not there yet

 https://github.com/github/roadmap/issues/528 
https://github.com/actions/runner-images/issues/2187

**Comment by Barre** [comment]
Fixed in https://github.com/Barre/privaxy/releases/tag/v0.5.0
