### ISSUE TITLE
How to use proxy Exclusions

### ISSUE THREAD

**Issue by gitze** [Barre/privaxy#51]
Hi 
I want to exclude complete domains (incl. all subdomains) from the proxy and bypass the MITM functionality.
If I use the full domain incl. subdomain, this feature is working and the certificate will stay unchanged.
e.g. 
Privaxy Exclusions: www.ubs.com
URL: www.ubs.com -> cert original

But exclude all possible subdomains from ubs.com did not work:
Privaxy Exclusions: ubs.com
URL: www.ubs.com -> privaxy cert
URL: ebanking-de2.ubs.com -> privaxy cert

How can I exclude full domains and set them as transparent? Which syntax is needed?
Thanks for advice

**Comment by Barre** [comment]
Hi,

That's what happens here: https://github.com/Barre/privaxy/blob/main/privaxy/src/server/proxy/exclusions.rs#L9
I didn't implement wildcards in configurable exclusions as I didn't want to expose the `glob` crate to untrusted input as it's not really designed to be used as the way that privaxy does.

I'll work on removing this dependency and exposing wildcard matching to configurable exclusions in the next few days.

**Comment by gitze** [comment]
Thank you :-)

**Comment by Barre** [comment]
Done in 0.5.2: https://github.com/Barre/privaxy/releases/tag/v0.5.2
