### ISSUE TITLE
Windows pre-built installation fails midway

### ISSUE THREAD

**Issue by ferninator2** [Barre/privaxy#57]
Hello and thank you for developing such a wonderful application.

I tried to install Privaxy on my computer, but after the PowerShell window appears during the installation, a dialog box appeared, saying

> There is a problem with this Windows Installer package. A program run as part of the setup did not finish as expected. Contact your support personnel or package vendor.

After pressing OK, the installer says

> Privaxy Setup Wizard ended prematurely because of an error. Your system has not been modified. [...]

OS version: Windows 7 Professional SP1 (64 bit)
Privaxy version: 0.5.2 (from Github releases)

I am willing to provide more details to resolve this issue. Thanks.

**Comment by Barre** [comment]
Can you try to install webview2 manually? https://developer.microsoft.com/en-us/microsoft-edge/webview2/#download-section

**Comment by ferninator2** [comment]
Hello, when I tried installing WebView2 manually, using the standalone installer, the installer said:
> The installer archive is corrupted or invalid. Please download Microsoft Edge again.

I tried installing Microsoft Edge (not WebView2), but the Microsoft Edge installer said:
> Unable to connect to the Internet. If you use a firewall, please allowlist MicrosoftEdgeUpdate.exe.

I also tried to install WebView2 using the online installer, but it also said the "Unable to connect" error.

I haven't used any firewall to block Microsoft Edge, and since I haven't installed it yet, I cannot allowlist it either.

Hope this helps.

**Comment by Rusenche** [comment]
![Error](https://user-images.githubusercontent.com/18578128/211561442-7ffc300e-dc06-476a-97c0-df9bcf61f76b.png)

**Comment by Barre** [comment]
> Hello, when I tried installing WebView2 manually, using the standalone installer, the installer said:
> 
> > The installer archive is corrupted or invalid. Please download Microsoft Edge again.
> 
> 
> 
> I tried installing Microsoft Edge (not WebView2), but the Microsoft Edge installer said:
> 
> > Unable to connect to the Internet. If you use a firewall, please allowlist MicrosoftEdgeUpdate.exe.
> 
> 
> 
> I also tried to install WebView2 using the online installer, but it also said the "Unable to connect" error.
> 
> 
> 
> I tried redownloading the installers, but it didn't work either.
> 
> 
> 
> I haven't used any firewall to block Microsoft Edge, and since I haven't installed it yet, I cannot allowlist it either.
> 
> 
> 
> Hope this helps.

Can you try to install using the "Evergreen Standalone Installer" from the link above?

**Comment by pmmlpmmlpmmlpmml** [comment]
Hello, I am a newbie. Tell me how to configure the program. I will check its functionality and it does not want to work. Or did I configure something wrong? My system is Windows 11.

**Comment by ferninator2** [comment]
Hello, sorry for the late reply :)

The findings in my previous comment, regarding the Evergreen Standalone Installer (which I referred to as the standalone installer) and the Evergreen Bootstrapper (which I referred to as the online installer), were downloaded from the link you provided.

**Comment by Barre** [comment]
Hello,

Can you create an issue there: https://github.com/MicrosoftEdge/WebView2Feedback/issues and link back the link here?

**Comment by ferninator2** [comment]
Sure, here's the issue I created: MicrosoftEdge/WebView2Feedback/issues/3122

Since Windows 7 is going out-of-support, I have zero expectations that it will be fixed. I think the more viable solution would be to have a CLI-only binary for Windows so that systems that don't support WebView 2 can still use Privaxy.

**Comment by Barre** [comment]
I fixed windows nogui builds earlier https://github.com/Barre/privaxy/commit/7f0419111b0d258b4b53122a373a0532d228fbe3

I just added the build artifact to the latest release https://github.com/Barre/privaxy/releases/tag/v0.5.2

**Comment by ferninator2** [comment]
Thanks! I'm currently testing the nogui build you posted.

**Comment by ferninator2** [comment]
I just finished testing the Windows nogui build you posted and it launches perfectly :)

I encountered a few issues, which I used workarounds to solve:

- not being able to download the CA certificate from the webpage, because even though `127.0.0.1:8100` works as a proxy, it doesn't have a GUI when I visit it as a webpage - I solved this by manually copying the certificate text from the `.privaxy\config` file into a new text file then importing into Windows (Note: only copy the certificate, not the private key)
- Firefox refusing to use the certificate - I solved this by importing the certificate to `Security > Certificates > View > Certificates > Authorities` in the `about:preferences#privacy` page

Now, besides not being able to see the proxied, blocked, and modified URLs in real time (and the other issues such as failing to perform handshakes sometimes), everything works great! Thank you very much!

PS: Now I'm not sure whether to close this issue because technically the original issue was never fixed. Should this issue be closed?

**Comment by Barre** [comment]
> not being able to download the CA certificate from the webpage, because even though 127.0.0.1:8100 works as a proxy, it doesn't have a GUI when I visit it as a webpage - I solved this by manually copying the certificate text from the .privaxy\config file into a new text file then importing into Windows (Note: only copy the certificate, not the private key)

I guess I could this by just writing a copy of the certificate alongside the config file.

> PS: Now I'm not sure whether to close this issue because technically the original issue was never fixed. Should this issue be closed?

I guess you are right, I'll close this for now.
