### ISSUE TITLE
 Failing to start on Ubuntu

### ISSUE THREAD

**Issue by L8X** [Barre/privaxy#65]
(privaxy:6458): Gtk-WARNING **: 19:07:28.418: cannot open display:

**Comment by Barre** [comment]
Do you have an X server running? 
Are you intending to use privaxy on an headless machine?

**Comment by Barre** [comment]
> what's an X server?

https://x.org/wiki/

> headless, you mean with no interface? If yes, then yes.

So then, you need to download a "nogui" version https://github.com/Barre/privaxy/releases/tag/v0.5.2
