### ISSUE TITLE
Mobile device support

### ISSUE THREAD

**Issue by mrbluecoat** [Barre/privaxy#79]
Any plans to support Android or iOS?

**Comment by dascgit** [comment]
@mrbluecoat What do you mean by support? You can connect to privaxy. Just configure the proxy on your Android and iOS device.

**Comment by mrbluecoat** [comment]
Sorry, I meant a dedicated app. I'll close since native proxy setting is the recommended solution.

**Comment by mrbluecoat** [comment]
p.s. many apps ignore the device proxy settings so this protection will be incomplete.

https://stackoverflow.com/questions/24417242/do-android-proxy-settings-apply-to-all-apps-on-the-device#24417392
