### ISSUE TITLE
openwrt support

### ISSUE THREAD

**Issue by hululu1068** [Barre/privaxy#82]
This is a really cool project!
It would be great to enable it to run on openwrt, so that it can provide services for all devices on the `LAN`.
Tried `AdguardHome` and `pi-hole`, but they are not as good as `privaxy`.
Looking forward to your good news！

**Comment by Barre** [comment]
Hi,

I am not sure if that would be a good idea as usually, Openwrt devices are very underpowered and would perform very poorly with privaxy.

I'm open to a contribution in this direction though.
