### ISSUE TITLE
Privaxy dropped support for ARM in 0.5.2?

### ISSUE THREAD

**Issue by TheBrenny** [Barre/privaxy#84]
During the bump from 0.5.1 to 0.5.2, [it looks like the ARM target was dropped](https://github.com/Barre/privaxy/compare/v0.5.1...v0.5.2#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03fL84-L87). Was this intentional?

**Comment by Barre** [comment]
Hi,

ARM support on linux wasn't dropped. You can build it manually if needed.
