### ISSUE TITLE
Discord not starting when using Proxy

### ISSUE THREAD

**Issue by BLACK4585** [Barre/privaxy#89]
I'm using Privaxy now since a few days and I configured it in the Windows Proxy settings to route all traffic through the given IP and Port. But when I start Discord, it stays in the loading screen. I have to completely disable the Proxy in the Windows settings, then it starts. When it's running, I can enable the Proxy again and it works flawlessly. I looked up the requests and filter lists, but all domains having something with "discord" in their name are not blocked.
Is there maybe a known solution for that?

**Comment by nameniok** [comment]
Add `gateway.discord.gg` or `gateway.discord.*` to Settings -> Exclusions

**Comment by BLACK4585** [comment]
Fixed, thx
